[build]
  publish = "dist"
  command = "npm ci --include=optional && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_CONFIG_OPTIONAL = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
